database:
  host: your_host
  port: 3306
  user: your_user
  password: your_password
  dbname: cloud_bill
  debug: false

usd_to_cny_exchange_rate: 7.0


cloud:
  - account_alias_name: your_account_alias_name
    cloud_provider: tencent
    fetch_per_second: 5
    main_account_id: your_main_account_id
    access_key_id: your_key_id
    access_key_secret: your_key_secret
    enabled: true
  - account_alias_name: your_account_alias_name2
    cloud_provider: tencent
    fetch_per_second: 5
    main_account_id: your_main_account_id2
    access_key_id: your_key_id2
    access_key_secret: your_key_secret2
    enabled: false
  - account_alias_name: your_account_alias_name
    cloud_provider: aliyun
    fetch_per_second: 10
    main_account_id: your_main_account_id
    access_key_id: your_key_id
    access_key_secret: your_key_secret
    enabled: true
  - account_alias_name: your_account_alias_name
    cloud_provider: ucloud
    fetch_per_second: 5
    main_account_id: your_main_account_id
    access_key_id: your_key_id
    access_key_secret: your_key_secret
    enabled: true
  - account_alias_name: your_account_alias_name
    cloud_provider: aws
    fetch_per_second: 5
    main_account_id: your_main_account_id
    access_key_id: your_key_id
    access_key_secret: your_key_secret
    enabled: true